use stream_copy_to_stream
prasathmani/tinyfilemanager pull request #1014
Opened 2023-04-09 11:39 UTC by divinity76

it's simpler, and should be faster.
For example, stream_copy_to_stream can use sendfile ( https://man7.org/linux/man-pages/man2/sendfile.2.html ) on operating systems supporting it, which is faster and use less RAM than fread()+fwrite() (because it avoids copying data to/from userland, doing the copy entirely in-kernel~)

2023-04-09 17:12 UTC, ner00 commented
This might be a problem under 32bit environments with files bigger than 4GiB. 
Also, on Windows, PHP 64-bit up to v8.0.7 seems to have an issue with files bigger than 4 GiB regardless.

At best `stream_copy_to_stream` would need to check if the input file is supported by the server function or if it's going to end with a corrupt output.

2023-04-09 17:52 UTC, ner00 requested changes
Check if server can write files bigger than 4GiB, especially considering PHP bugs [#74395](https://bugs.php.net/bug.php?id=74395) and [#81145](https://bugs.php.net/bug.php?id=81145).

2023-04-10 10:34 UTC, divinity76 commented
@ner00 even just testing 32bit php5.5 is very cubersome; i installed a 32bit debian 11 VM, couldn't find a php5.5 pre-built binary, tried to compile php5.5, but building php5.5 from source requires an ancient 2012 version of GNU Bison (2.7), couldn't find a pre-built bison2.7, trying to build bison2.7 from source ends with this error:
```
  CC       fprintf.o
  CC       fseterr.o
fseterr.c: In function 'fseterr':
fseterr.c:77:3: error: #error "Please port gnulib fseterr.c to your platform! Look at the definitions of ferror and clearerr on your system, then report this to bug-gnulib."
   77 |  #error "Please port gnulib fseterr.c to your platform! Look at the definitions of ferror and clearerr on your system, then report this to bug-gnulib."
      |   ^~~~~
make[3]: *** [Makefile:1915: fseterr.o] Error 1
make[3]: Leaving directory '/temp/bison/bison-2.7.1/lib'
make[2]: *** [Makefile:1672: all] Error 2
make[2]: Leaving directory '/temp/bison/bison-2.7.1/lib'
make[1]: *** [Makefile:1558: all-recursive] Error 1
make[1]: Leaving directory '/temp/bison/bison-2.7.1'
make: *** [Makefile:1488: all] Error 2
root@32bitdebian:/temp/bison/bison-2.7.1# 
```
googlging that lead me to this patch: https://github.com/rdslw/openwrt/blob/e5d47f32131849a69a9267de51a30d6be1f0d0ac/tools/bison/patches/110-glibc-change-work-around.patch

after applying that patch to bison, i was finally able to get bison2.7 to build, and finally able to build PHP5.5 with
```
git clone -b 'PHP-5.5' --depth 1 https://github.com/php/php-src.git && \
cd 'php-src' && \
./buildconf && \
./configure --disable-all --disable-cgi --enable-cli && \
make clean && \
make -j $(nproc)
```
and voila
```
root@32bitdebian:/temp/php/php-src# sapi/cli/php -v
PHP 5.5.38 (cli) (built: Apr 10 2023 12:27:35) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
```
and now to test stream_copy_to_stream on a 5GB file: 
```
root@32bitdebian:/temp/php/php-src# truncate -s 5G 5g.bin
root@32bitdebian:/temp/php/php-src# du -h --apparent-size 5g.bin 
5.0G	5g.bin
root@32bitdebian:/temp/php/php-src# du --bytes --apparent-size 5g.bin 
5368709120	5g.bin
root@32bitdebian:/temp/php/php-src# cat test.php
<?php
$h = fopen("5g.bin","rb");
$h2 = fopen("5g.copy.bin","wb");
$ret = stream_copy_to_stream($h,$h2);
var_dump($ret);

root@32bitdebian:/temp/php/php-src# time sapi/cli/php test.php

Warning: fopen(5g.bin): failed to open stream: Value too large for defined data type in /temp/php/php-src/test.php on line 2

Warning: stream_copy_to_stream() expects parameter 1 to be resource, boolean given in /temp/php/php-src/test.php on line 4
bool(false)

real	0m0.007s
user	0m0.007s
sys	0m0.001s
```

well.... that was certainly an unexpected result, but the problem isn't stream_copy_to_stream, it's fopen! :O (at least on 32bit php5.5.38)

2023-04-10 10:43 UTC, divinity76 commented
trying the same on a file that is exactly 0xFFFFFFFF ( 4294967295 ) bytes, aka the max possible value of a uint32_t (keep in mind, 32bit php's int is int32_t, not uint32_t) yield the same fopen error.

 trying on a file that is exactly 0x7FFFFFFF (2147483647 ) bytes, aka 32bit PHP's PHP_INT_MAX yields: 
 
```
root@32bitdebian:/temp/php/php-src# time sapi/cli/php test.php
int(2147483647)

real	0m36.857s
user	0m0.261s
sys	0m36.576s
root@32bitdebian:/temp/php/php-src# du --bytes --apparent-size 4g.copy.bin 
2147483647	4g.copy.bin
```

success!

2023-04-10 11:26 UTC, divinity76 commented
to keep it simple, how about we just do
```php
if (PHP_VERSION_ID < 80009) {
    // workaround https://bugs.php.net/bug.php?id=81145
    while ($buff = fread($in, 4096)) { fwrite($out, $buff); }
} else {
    stream_copy_to_stream($in, $out);
}
```
?

2023-04-10 11:33 UTC, divinity76 commented
ouch shit, just found a bug in the original code: https://3v4l.org/PItRM
the while loop should be something like
```
while (!in_array($buff = fread($in, 4096), array("", false), true)) { fwrite($out, $buff); }
```
otherwise it will fail on files being 4097 bytes and ending with `0` :O

2023-04-10 11:41 UTC, divinity76 commented
PR updated, fixed the while loop early return, and only use stream_copy_to_stream on php >= 8.0.9 because of https://bugs.php.net/bug.php?id=81145

2023-04-10 15:35 UTC, ner00 approved these changes
Looks good to me. 

Seems to have an average performance increase anywhere between 15% to 30% using `stream_copy_to_stream`

2023-04-10 16:22 UTC, prasathmani commented
@divinity76  and @ner00 thanks for your support, I'll verify and merge sometime soon.

2023-04-10 17:29 UTC, divinity76 commented
when this is merged, it will also fix #1016 :)

2023-04-21 04:35 UTC, prasathmani approved these changes

2023-04-21 04:35 UTC, merged