Date Modified in file view
prasathmani/tinyfilemanager pull request #1250
Opened 2024-11-14 23:27 UTC by ner00

2025-01-23 01:57 UTC, prasathmani requested changes

2025-01-23 01:57 UTC, prasathmani commented on tinyfilemanager.php
> +                <li class="list-group-item"><strong>Date Modified:</strong> <?php echo date(FM_DATETIME_FORMAT, filemtime($file_path)); ?></li>
can you add translation support?

2025-01-31 22:54 UTC, ner00 commented on tinyfilemanager.php
> +                <li class="list-group-item"><strong>Date Modified:</strong> <?php echo date(FM_DATETIME_FORMAT, filemtime($file_path)); ?></li>
I can, but `File size` and `MIME-type` are also untranslated, do you want me to add those too to this commit?
https://github.com/prasathmani/tinyfilemanager/blob/8c78bc78f9bf285115759d7d0e5108bc8ae08a4c/tinyfilemanager.php#L1772
https://github.com/prasathmani/tinyfilemanager/blob/8c78bc78f9bf285115759d7d0e5108bc8ae08a4c/tinyfilemanager.php#L1773

2025-01-31 23:03 UTC, ner00 commented on tinyfilemanager.php
> +                <li class="list-group-item"><strong>Date Modified:</strong> <?php echo date(FM_DATETIME_FORMAT, filemtime($file_path)); ?></li>
I guess yes.

2025-02-02 04:25 UTC, prasathmani approved these changes

2025-02-02 04:25 UTC, merged