Bug fix: Delete confirm dialog will work wrong aflter cancel.
prasathmani/tinyfilemanager pull request #942
Opened 2023-01-18 02:02 UTC by fbotp

Clicking and canceling the delete confirm dialog will cause the information when the last confirmation of deletion is the file/directory information of the first click on the delete button.
Example on [Demo](https://tinyfilemanager.github.io/demo/):
![屏幕录制2023-01-18-09 23 43](https://user-images.githubusercontent.com/46618620/213062758-483f8772-8ef2-4b80-aea1-791fdd7d501b.gif)

2023-01-18 03:45 UTC, prasathmani requested changes

2023-01-18 03:45 UTC, prasathmani commented on tinyfilemanager.php
> +        $("#confirmDialog-"+tplObj.id).on('hidden.bs.modal', function() {
as we are using same selector on next line as well, better catch the selector.
```js
const $confirmDailog = $("#confirmDialog-"+tplObj.id);
$confirmDailog.on('hidden.bs.modal', function() {..}
$confirmDailog.modal('show');

2023-01-18 09:44 UTC, fbotp commented
不好意思，第一次使用PR操作，请问我现在该应该做什么呢？

2023-01-19 16:11 UTC, prasathmani approved these changes

2023-01-19 16:11 UTC, merged